spring:
  thymeleaf:
    encoding: utf-8

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/rest_new
    password: 12345
  liquibase:
    change-log: db/changelog/changelog-master.yml
    enabled: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 8081